import { after, before, test } from 'node:test';
import assert from 'node:assert/strict';
import type { Server } from 'node:http';
import { connectToTestDatabase, resetTestDatabase } from './helpers/test-database';

let server: Server; let baseUrl = ''; let participantCookie = ''; let otherParticipantCookie = ''; let coachCookie = ''; let createSessionToken: () => string; let hashSessionToken: (token: string) => string; let sessionCookie = '';
let sequence = 0;

async function cookie(personId: number) { const token = createSessionToken(); const client = await connectToTestDatabase(); await client.query("insert into app_session (person_id, token_hash, expires_at) values ($1, $2, now() + interval '1 hour')", [personId, hashSessionToken(token)]); await client.end(); return `${sessionCookie}=${token}`; }
async function createSession(roomId: number, coachId = 3, capacityFill = 0, dayOffset = sequence++) {
  const client = await connectToTestDatabase(); const start = new Date(Date.UTC(2030, 0, 7 + dayOffset, 15, 0, 0)); const end = new Date(start.getTime() + 60 * 60 * 1000);
  const result = await client.query<{ id: number }>("insert into session (room_id, coach_id, discipline, session_type, status, starts_at, ends_at, room_fee_credits, seat_fee_credits) values ($1, $2, 'test', 'standard', 'scheduled', $3, $4, 40, 20) returning id", [roomId, coachId, start, end]);
  for (let index = 0; index < capacityFill; index++) await client.query("insert into enrolment (session_id, person_id, status, credits_charged, credits_refunded, enrolled_at) values ($1, $2, 'active', 20, 0, now())", [result.rows[0].id, 4 + index]);
  await client.end(); return result.rows[0].id;
}
async function enrol(cookieValue: string, id: number) { return fetch(`${baseUrl}/api/sessions/${id}/enrolments`, { method: 'POST', headers: { Cookie: cookieValue } }); }

before(async () => { process.env.SESSION_SECRET = 'atrium-test-secret'; process.env.DATABASE_URL = process.env.TEST_DATABASE_URL; const auth = await import('../src/auth'); const app = await import('../src/app'); createSessionToken = auth.createSessionToken; hashSessionToken = auth.hashSessionToken; sessionCookie = auth.SESSION_COOKIE; await resetTestDatabase(); participantCookie = await cookie(2); otherParticipantCookie = await cookie(4); coachCookie = await cookie(3); server = app.createApp().listen(0); await new Promise<void>((resolve) => server.once('listening', resolve)); const address = server.address(); assert.ok(address && typeof address !== 'string'); baseUrl = `http://127.0.0.1:${address.port}`; });
after(async () => { await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); });

test('a participant enrols once, pays the seat fee, and sees only their own booking', async () => { const id = await createSession(1); const before = await connectToTestDatabase(); const credits = (await before.query<{ credits: number }>('select credits from person where id = 2')).rows[0].credits; await before.end(); const response = await enrol(participantCookie, id); assert.equal(response.status, 201); assert.equal((await enrol(participantCookie, id)).status, 409); const mine = await fetch(`${baseUrl}/api/sessions/mine/enrolments`, { headers: { Cookie: participantCookie } }); assert.equal(mine.status, 200); assert.equal((await mine.json()).some((row: { session_id: number }) => row.session_id === id), true); const after = await connectToTestDatabase(); assert.equal((await after.query<{ credits: number }>('select credits from person where id = 2')).rows[0].credits, credits - 20); await after.end(); });
test('enrolment rejects a full room, own session, and overlapping commitment', async () => { const full = await createSession(5, 3, 6); assert.equal((await enrol(participantCookie, full)).status, 409); const own = await createSession(2, 3); assert.equal((await enrol(coachCookie, own)).status, 403); const day = sequence++; const first = await createSession(3, 3, 0, day); assert.equal((await enrol(participantCookie, first)).status, 201); const second = await createSession(4, 3, 0, day); assert.equal((await enrol(participantCookie, second)).status, 409); });
test('simultaneous enrolments cannot exceed capacity', async () => { const id = await createSession(5, 3, 5); const results = await Promise.all([enrol(participantCookie, id), enrol(otherParticipantCookie, id)]); assert.deepEqual(results.map((response) => response.status).sort(), [201, 409]); });
test('a participant cancellation returns the documented full refund with 48 hours notice', async () => { const id = await createSession(6); const client = await connectToTestDatabase(); const before = (await client.query<{ credits: number }>('select credits from person where id = 4')).rows[0].credits; await client.end(); assert.equal((await enrol(otherParticipantCookie, id)).status, 201); const response = await fetch(`${baseUrl}/api/sessions/${id}/enrolments/cancel`, { method: 'POST', headers: { Cookie: otherParticipantCookie } }); const body = await response.json(); assert.equal(response.status, 200); assert.equal(body.credits_refunded, 20); const verify = await connectToTestDatabase(); assert.equal((await verify.query<{ credits: number }>('select credits from person where id = 4')).rows[0].credits, before); await verify.end(); });
